services:
  mongo:
    image: 'mongo'
    networks:
      - backend
    volumes:
      - './data:/data/db'
    ports:
      - 27017:27017
  server:
    build: ./backend
    networks:
      - backend
    depends_on:
      - mongo
    env_file: './backend/docker.env'
  frontend:
    build: ./frontend
    networks:
      - frontend
    env_file: './frontend/docker.env'
  nginx:
    image: 'nginx'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - frontend
      - backend
    depends_on:
      - frontend
    ports:
      - 80:80

networks:
  frontend:
  backend: