apiVersion: v1
kind: ConfigMap
metadata:
  name: server-conf
data:
  port: '4000'
  mongo-host: mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.default.svc.cluster.local:27017?replicaSet=rs0
  frontend-url: 'http://frontend:3000/'